// GENERATED by struct2ts.mjs from: mrson-core.struct.json, events.struct.json, ops.struct.json, commits.struct.json
// Do not edit by hand.

export type Vec3 = number[];

export type RGBA = number[];

export type Matrix16 = number[];

export interface BlobRef {
  hash: string;
  dtype?: string;
  count?: number;
  comps?: number;
  size?: string;
  codec?: string;
}

export interface ZarrDesc {
  shape: number[];
  chunks: number[];
  chunkGrid: number[];
  dtype: string;
  bytes?: string;
  chunkHashes?: Record<string, string>;
  dir?: string;
  dataset?: string;
}

export type Refs = Record<string, string[]>;

export type Attrs = Record<string, string>;

export type Blobs = Record<string, BlobRef>;

export interface Code {
  scheme: string;
  value: string;
  meaning?: string;
}

export interface Source {
  mrmlClass?: string;
  producer?: string;
  producedAt?: string;
  derivedFrom?: string[];
}

export interface DicomBag {
  sopClassUID?: string;
  seriesInstanceUID?: string;
  frameOfReferenceUID?: string;
  tags?: Record<string, string>;
}

export interface Node {
  id: string;
  name?: string;
  frame?: string;
  refs?: Refs;
  attrs?: Attrs;
  blobs?: Blobs;
  dicom?: DicomBag;
  source?: Source;
}

export interface DisplayableNode extends Node {

}

export interface ImageNode extends DisplayableNode {
  dims: number[];
  ijkToRAS: Matrix16;
  voxelType?: string;
  comps?: number;
  zarr?: ZarrDesc;
}

export interface MeshNode extends DisplayableNode {

}

export interface Segment {
  id: string;
  name?: string;
  color?: RGBA;
  labelValue?: number;
  terminology?: Code;
}

export interface SegmentationNode extends DisplayableNode {
  segments: Segment[];
  referenceImage?: string;
}

export interface ControlPoint {
  label?: string;
  position: Vec3;
  selected?: boolean;
}

export interface MarkupNode extends DisplayableNode {
  markupType: "fiducial" | "line" | "angle" | "curve" | "closedcurve" | "plane" | "roi";
  controlPoints?: ControlPoint[];
  center?: Vec3;
  size?: Vec3;
}

export interface TransformNode extends Node {
  transformType: "linear" | "bspline" | "grid" | "thinplate" | "composite";
  toParent?: Matrix16;
}

export interface CameraNode extends Node {
  position: Vec3;
  focalPoint: Vec3;
  viewUp: Vec3;
  viewAngle?: number;
  parallelScale?: number;
}

export interface ViewNode extends Node {
  kind: "3d" | "slice";
  layoutName?: string;
  orientation?: string;
  sliceToRAS?: Matrix16;
  xyToRAS?: Matrix16;
  dimensions?: number[];
  fieldOfView?: Vec3;
}

export interface ColorStop {
  value: number;
  rgba: RGBA;
}

export interface OpacityStop {
  value: number;
  opacity: number;
}

export interface TransferFunctionNode extends Node {
  colorStops?: ColorStop[];
  scalarOpacity?: OpacityStop[];
  gradientOpacity?: OpacityStop[];
  shade?: boolean;
}

export interface DisplayNode extends Node {
  viewRefs?: string[];
  visible?: boolean;
}

export interface ScalarVolumeDisplayNode extends DisplayNode {
  window?: number;
  level?: number;
  color?: RGBA;
  interpolate?: boolean;
}

export interface VolumeRenderingDisplayNode extends DisplayNode {
  technique?: string;
  cropEnabled?: boolean;
}

export interface ModelDisplayNode extends DisplayNode {
  color?: RGBA;
  opacity?: number;
  representation?: "points" | "wireframe" | "surface";
  edgeVisibility?: boolean;
}

export interface MarkupDisplayNode extends DisplayNode {
  color?: RGBA;
  selectedColor?: RGBA;
  glyphScale?: number;
  textScale?: number;
}

export interface LayoutNode extends Node {
  arrangement?: number;
  arrangementName?: string;
}

export type AnyNode =
  | ({ type: "layout" } & LayoutNode)
  | ({ type: "image" } & ImageNode)
  | ({ type: "mesh" } & MeshNode)
  | ({ type: "segmentation" } & SegmentationNode)
  | ({ type: "markup" } & MarkupNode)
  | ({ type: "transform" } & TransformNode)
  | ({ type: "camera" } & CameraNode)
  | ({ type: "view" } & ViewNode)
  | ({ type: "transferFunction" } & TransferFunctionNode)
  | ({ type: "scalarVolumeDisplay" } & ScalarVolumeDisplayNode)
  | ({ type: "volumeRenderingDisplay" } & VolumeRenderingDisplayNode)
  | ({ type: "modelDisplay" } & ModelDisplayNode)
  | ({ type: "markupDisplay" } & MarkupDisplayNode);

export interface Scene {
  mrson: number;
  blobBase?: string;
  nodes: Record<string, AnyNode>;
}

export interface LiveEvent {
  sourceId: string;
  t?: number;
}

export interface ModifiedEvent extends LiveEvent {

}

export interface TransformModifiedEvent extends LiveEvent {

}

export interface DisplayModifiedEvent extends LiveEvent {

}

export interface CameraModifiedEvent extends LiveEvent {
  position: Vec3;
  focalPoint: Vec3;
  viewUp: Vec3;
  viewAngle?: number;
}

export interface MarkupPointModifiedEvent extends LiveEvent {
  pointIndex: number;
  position: Vec3;
}

export interface SelectionEvent extends LiveEvent {
  selectedIds: string[];
}

export interface NodeAddedEvent extends LiveEvent {
  nodeId: string;
  nodeClass: string;
}

export interface NodeRemovedEvent extends LiveEvent {
  nodeId: string;
}

export type AnyEvent =
  | ({ event: "Modified" } & ModifiedEvent)
  | ({ event: "TransformModified" } & TransformModifiedEvent)
  | ({ event: "DisplayModified" } & DisplayModifiedEvent)
  | ({ event: "CameraModified" } & CameraModifiedEvent)
  | ({ event: "MarkupPointModified" } & MarkupPointModifiedEvent)
  | ({ event: "Selection" } & SelectionEvent)
  | ({ event: "NodeAdded" } & NodeAddedEvent)
  | ({ event: "NodeRemoved" } & NodeRemovedEvent);

export interface Op {
  id: string;
  v?: number;
  origin?: string;
  role?: "human" | "agent" | "module" | "automated";
}

export interface PutOp extends Op {
  node: unknown;
}

export interface PatchOp extends Op {
  path: string;
  value: unknown;
}

export interface DelOp extends Op {

}

export interface CmdOp extends Op {
  cmd: string;
  args?: unknown;
}

export type AnyOp =
  | ({ op: "put" } & PutOp)
  | ({ op: "patch" } & PatchOp)
  | ({ op: "del" } & DelOp)
  | ({ op: "cmd" } & CmdOp);

export type ContentHash = string;

export interface BranchPoint {
  commit: ContentHash;
  offset: number;
}

export interface Commit {
  hash: ContentHash;
  parents: ContentHash[];
  base?: BranchPoint;
  t: string;
  author?: string;
  role?: "human" | "agent" | "module" | "automated";
  message?: string;
  ops: unknown[];
  tree?: ContentHash;
}

export interface Ref {
  name: string;
  commit: ContentHash;
}

export interface Stream {
  mrson: number;
  id: string;
  root?: ContentHash;
  head: ContentHash;
  blobBase?: string;
  commits?: Commit[];
  refs?: Ref[];
}

export interface Fork {
  mrson: number;
  id: string;
  forkOf: string;
  base: BranchPoint;
  head: ContentHash;
  blobBase?: string;
  commits?: Commit[];
}

export interface PullRequest {
  id: string;
  fork: string;
  into: string;
  base: BranchPoint;
  head: ContentHash;
  title?: string;
  message?: string;
  state: "open" | "merged" | "declined";
}
