#!/usr/bin/env node
// struct2ts — a minimal JSON Structure -> TypeScript emitter for mrson.
// Covers exactly the JSON Structure subset mrson uses: object + $extends (single/array),
// choice + selector (discriminated union), $ref, array/set, map, tuple, inline enum,
// required/optional, abstract, and the JSON Structure primitive set.
// This is intentionally small and hand-owned (structurize codegen is broken in 3.9.0);
// extend it as the schema grows.
//
// usage: node struct2ts.mjs <schema.struct.json> [more.struct.json ...]

import { readFileSync } from "node:fs";

const PRIM = {
  string: "string", uri: "string", uuid: "string", jsonpointer: "string",
  date: "string", datetime: "string", time: "string", duration: "string",
  binary: "string", boolean: "boolean", null: "null",
  number: "number", integer: "number",
  int8: "number", int16: "number", int32: "number", float8: "number", float: "number", double: "number",
  // 64-bit+ carried as strings (JSON Structure safe-int rule)
  int64: "string", int128: "string", uint8: "number", uint16: "number", uint32: "number",
  uint64: "string", uint128: "string", decimal: "string",
};

const refName = (p) => p.split("/").pop();

// Render a JSON Structure type node -> a TS type expression.
function tsType(node) {
  if (!node || typeof node !== "object") return "unknown";
  const t = node.type;
  if (t && typeof t === "object" && t.$ref) return refName(t.$ref);      // { "type": { "$ref": ... } }
  if (typeof t !== "string") return "unknown";
  if (node.enum && Array.isArray(node.enum)) {                            // inline enum -> literal union
    return node.enum.map((v) => (typeof v === "string" ? JSON.stringify(v) : String(v))).join(" | ");
  }
  switch (t) {
    case "array": case "set": return `${tsType(node.items)}[]`;
    case "map": return `Record<string, ${tsType(node.values)}>`;
    case "tuple": return `[${(node.tuple || []).map((k) => tsType(node.properties[k])).join(", ")}]`;
    case "object": return objectLiteral(node);                           // inline object
    case "any": return "unknown";
    default: return PRIM[t] ?? "unknown";
  }
}

function objectLiteral(node) {
  const req = new Set(node.required || []);
  const props = Object.entries(node.properties || {}).map(
    ([k, v]) => `  ${k}${req.has(k) ? "" : "?"}: ${tsType(v)};`
  );
  return props.length ? `{\n${props.join("\n")}\n}` : "{}";
}

function emit(schemaPath, out, seen) {
  const doc = JSON.parse(readFileSync(schemaPath, "utf8"));
  const defs = doc.definitions || {};
  for (const [name, def] of Object.entries(defs)) {
    if (seen.has(name)) continue;   // shared type (e.g. Vec3) already emitted from an earlier input
    seen.add(name);
    if (def.type === "choice") {                                          // discriminated union
      const sel = def.selector;
      const members = Object.entries(def.choices).map(([key, c]) => {
        const ref = c.type?.$ref ? refName(c.type.$ref) : tsType(c);
        return sel ? `({ ${sel}: ${JSON.stringify(key)} } & ${ref})` : `({ ${JSON.stringify(key)}: ${ref} })`;
      });
      out.push(`export type ${name} =\n  | ${members.join("\n  | ")};\n`);
    } else if (def.type === "object") {                                   // interface (+ $extends)
      const bases = def.$extends ? [].concat(def.$extends).map(refName) : [];
      const ext = bases.length ? ` extends ${bases.join(", ")}` : "";
      const req = new Set(def.required || []);
      const body = Object.entries(def.properties || {}).map(
        ([k, v]) => `  ${k}${req.has(k) ? "" : "?"}: ${tsType(v)};`
      );
      out.push(`export interface ${name}${ext} {\n${body.join("\n")}\n}\n`);
    } else {                                                              // named alias (array/map/primitive)
      out.push(`export type ${name} = ${tsType(def)};\n`);
    }
  }
}

const files = process.argv.slice(2);
if (!files.length) { console.error("usage: struct2ts.mjs <schema.struct.json> ..."); process.exit(1); }
const out = [`// GENERATED by struct2ts.mjs from: ${files.map((f) => f.split("/").pop()).join(", ")}`, `// Do not edit by hand.\n`];
const seen = new Set();
for (const f of files) emit(f, out, seen);
process.stdout.write(out.join("\n"));
